spring:
  config:
    activate:
      on-profile: secret-prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.DB_HOST }}
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}

mybatis:
  mapper-locations: mappers/**/*.xml
